---
version: 2

updates:
  - package-ecosystem: docker
    directories:
      - /bazarr
      - /calibre
      - /nzbget
      - /prowlarr
      - /qbittorrent
      - /radarr
      - /readarr
      - /sonarr
    groups:
      docker:
        patterns:
          - "*"
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
